# Generated by Django 5.0.1 on 2024-04-02 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_profile_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Profile',
        ),
    ]
