# Generated by Django 5.0.2 on 2024-03-29 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('required_skills', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
