# Generated by Django 5.0.2 on 2024-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='Profile_picsS'),
        ),
    ]
