# Generated by Django 5.0.1 on 2024-04-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
