# Generated by Django 5.0.1 on 2024-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
